version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3005:3005"
    environment:
      - NODE_ENV=development
    volumes:
      - ./.env.client:/app/.env.client
      - ./server/.env:/app/server/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musiclib
      MYSQL_USER: musiclib
      MYSQL_PASSWORD: musiclib_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data: