version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3005:3005"
    environment:
      - NODE_ENV=development
    volumes:
      - ./.env.client:/app/.env.client
      - ./server/.env:/app/server/.env
      - ./server/storage:/app/server/storage
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-dev_root_password_change_in_production}
      MYSQL_DATABASE: musiclib
      MYSQL_USER: musiclib
      MYSQL_PASSWORD: ${DB_PASSWORD:-dev_password_change_in_production}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  db_data:
  redis_data: